### ISSUE TITLE
please put usage examples at the top of the readme

### ISSUE THREAD

**Issue by bionicles** [hyperhyperspace/hyperhyperspace-core#6]
would you please be openminded to put a code block near the top of the readme which explains how one would set this up and use it?

that would make it easier to evaluate and understand the API

**Comment by sbazerque** [comment]
Thanks for the suggestion! We'll add a code example to try to clarify it a bit more.

**Comment by sbazerque** [comment]
OK, tried but I feel a self contained code example would be a bit too long at the top of the README file.

But I added a TLDR-style sentence, with a link to the shortest example we have.

Do you feel it is a bit clearer now, @bionicles?
